version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=tutoring_organization
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325