service: tutoring-ms-org

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  versionFunctions: false
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  memorySize: 256
  timeout: 15
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PORT: ${env:POSTGRES_PORT}
    POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_DB: ${env:POSTGRES_DB}
    AUTHORIZER_MS_AUTH: ${env:AUTHORIZER_MS_AUTH}
    SNS_CREATE_USER: ${env:SNS_CREATE_USER}
    SNS_REGION: ${env:SNS_REGION}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    STAGE: ${env:STAGE}
    IS_OFFLINE: ${env:IS_OFFLINE}
    SNS_CREATE_TUTORING: ${env:SNS_CREATE_TUTORING}
    SNS_CREATE_STUDY_GROUP: ${env:SNS_CREATE_STUDY_GROUP}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
            - 'lambda:*'
            - 'sqs:*'
            - 'sns:*'
            - 'execute-api:*'
          Resource: '*'

custom:
  baseAuthorizer:
    arn: ${self:provider.environment.AUTHORIZER_MS_AUTH}
    resultTtlInSeconds: 0
  localAuthorizer:
    name: authorization
    type: token
  prune:
    automatic: true
    includeLayers: true
    number: 3
  apigwBinary:
    types:
      - "multipart/form-data"
      - "image/jpeg"
      - "image/jpeg"
      - "image/pjpeg"
      - "image/png"
      - "image/jpg"
  functionsDir: src/4-framework/functions
  serverless-offline:
    httpPort: 4100
    lambdaPort: 4101
  serverless-offline-sns:
    port: 4099
    debug: true
  enable-functions:
    dev: true
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    packagerOptions:
      noFrozenLockfile: true
    includeModules:
      forceInclude:
        - pg
        - pg-hstore

plugins:
  - serverless-disable-functions
  - '@jhonpedro/serverless-offline-local-authorizers-plugin'
  - serverless-offline-sns
  - serverless-offline
  - serverless-webpack
  
functions:  
  - "${file(${self:custom.functionsDir}/user/user.yml)}"
  - "${file(${self:custom.functionsDir}/studyGroup/studyGroup.yml)}"
  - "${file(${self:custom.functionsDir}/post/post.yml)}"
  - "${file(${self:custom.functionsDir}/postReaction/postReaction.yml)}"
  - "${file(${self:custom.functionsDir}/studyGroupLeader/studyGroupLeader.yml)}"
  - "${file(${self:custom.functionsDir}/studyGroupStudent/studyGroupStudent.yml)}"
  - "${file(${self:custom.functionsDir}/tutoring/tutoring.yml)}"

resources:
  Resources:     
    CreateOrUpdateTutoringSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: tutoring-org-${self:provider.stage}-create-update-tutoring
    CreateOrUpdateStudyGroupSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: tutoring-org-${self:provider.stage}-create-update-study-group